### ISSUE TITLE
Feature Request: Authentication

### ISSUE THREAD

**Issue by keflavich** [astropy/pyvo#122]
Many different services need to authenticate using cookies or some sort of persistent session ID.  This functionality should be supported in a less-hacky way than needed at present (e.g., #107)

**Comment by keflavich** [comment]
Note that this is an extension beyond the VO standard, which we (@cbanek, @andamian, @bsipocz, @jcsegovia) agreed should live in pyvo.

**Comment by funbaker** [comment]
Well, this is service-specific, so i see no way to provide an explicit way to handle authentication without creating a bogus interface.

The most clean way of providing this functionallity that i can think of would be to expose the requests session object on service-object and/or query-method level.

**Comment by keflavich** [comment]
I agree that exposing the `Session` is the best way to go.  I would also suggest making it possible to create a new `Session` on demand rather than having a single `Session` created at import time, especially if there can be multiple different VO services that may require different credentials.

**Comment by andamian** [comment]
Authentication is part of the VO standard. Each end point of a service specifies the supported authentication method: cookies, sso, certificate etc.
I think that the session is an implementation detail and it shouldn't be exposed in the API. What we need instead is a placeholder for user credentials (cookies, certificates, etc.) that is passed into a service when the corresponding class is instantiated. The service class can then try to match the provided user credentials with the ones supported by the service and do the authentication. No credentials or mismatched credentials (cookies when the service accepts only certificates for ex) would result in anonymous access if that is supported by the end point or a "not authenticated" exception otherwise.
Java has the Subject class as the preferred mechanism for doing this kind of things. Subject can store user identities and credentials and code can be executed within the context of that subject. I don't know what the Python equivalent is. Has anyone come across something similar?

**Comment by funbaker** [comment]
@andamian Yes and no. Authentication methods are listed in the capabilities, but every service can also define their own subtype of SecurityMethod.

> I think that the session is an implementation detail and it shouldn't be exposed in the API

The session object is part of a well known and maintained project and thus safe to expose in the API https://2.python-requests.org/en/master/user/advanced/#session-objects

Note that pyvo is an API and not a user interface (thats what astroquery is destined to be), and that guessing about authentication could result in side-effects.

**Comment by pllim** [comment]
Maybe @tomdonaldson or @ceb8 can chime in on authentication given their work on the MAST side and its interface to `astroquery.mast`.

**Comment by ceb8** [comment]
@cam72cam implemented the current mast authentication in astroquery.

**Comment by cbanek** [comment]
Fixed by #157
