### ISSUE TITLE
pyvo has no attribute object2pos

### ISSUE THREAD

**Issue by cbanek** [astropy/pyvo#165]
So as a part of #159, I tried to run the scripts.  Here's what I get:

```
(env) [cbanek@cbanekpc scripts]$ python ex_casA_image_cat.py 
WARNING: UnknownElementWarning: None:1:1168: UnknownElementWarning: Unknown element mirrorURL [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:80:4018: UnknownElementWarning: Unknown element mirrorURL [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:80:4335: UnknownElementWarning: Unknown element mirrorURL [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:80:4647: UnknownElementWarning: Unknown element mirrorURL [pyvo.utils.xml.elements]
WARNING: UnknownElementWarning: None:80:4947: UnknownElementWarning: Unknown element mirrorURL [pyvo.utils.xml.elements]
Traceback (most recent call last):
  File "ex_casA_image_cat.py", line 8, in <module>
    pos = vo.object2pos('Cas A')
AttributeError: module 'pyvo' has no attribute 'object2pos'

(env) [cbanek@cbanekpc scripts]$ python ex_get_cutouts.py 
Traceback (most recent call last):
  File "ex_get_cutouts.py", line 9, in <module>
    mysources[src] = vo.object2pos(src)
AttributeError: module 'pyvo' has no attribute 'object2pos'
(env) [cbanek@cbanekpc scripts]$ 
```

Looks like this function is gone.  I don't see any current code that has this function name, but in #30 it looks like it worked.  Should I just get rid of these?  Or modify them to call something else?

**Comment by msdemlei** [comment]
On Mon, Aug 26, 2019 at 10:34:22PM -0700, Christine Banek wrote:
> Maybe this should be SkyCoord.from_name('')?

Yes, definitely.  I've not researched when object2pos vanished, but
whoever removed it probably figured there's no point replicating core
astropy functionality.

However, that's not nearly enough.

I wasn't aware that rather unsubtle changes happened when pyvo moved
to using RegTAP for querying the registry, so that needed some
updates, and SIAResults and SIARecord changed, too, since that script
was written.  Hm.

The upshot is that a fixed script looks quite a bit different.  Not
quite sure if github's mail interface can do attachments; if it
does, I'm attaching the fixed script.

Btw. this also includes a warning filter; the VOTable module shouts
at the (non-standard by UCD, standard by SIAP) UCDs, and that makes
the output of the script really unpleasant.  I give you a better
solution would be if astropy's VOTable parser would only spew out
such warnings if asked to do so (in general, they're not that
problematic to basic interoperability).  But that's for another
issue.

**Comment by funbaker** [comment]
> Yes, definitely.  I've not researched when object2pos vanished, but
whoever removed it probably figured there's no point replicating core
astropy functionality.

That was me ...

> I wasn't aware that rather unsubtle changes happened when pyvo moved
to using RegTAP for querying the registry, so that needed some
updates, and SIAResults and SIARecord changed, too, since that script
was written.  Hm.

... but apparently i forgot to modify the example as well.

Using `SkyCoord.from_name` instead should work.
