### ISSUE TITLE
For TAP or SIA results, support DataLink queries with multiple IDs

### ISSUE THREAD

**Issue by andamian** [astropy/pyvo#217]
Current implementation requires separate calls to DataLink for each of the records in the results returned by an SIA or TAP query. In practice, this sometimes proves inefficient.

I propose an optimization by which the API allows the user to send multiple IDs (batches) to the DataLink service. In our experience, the overhead for individual calls is too high. I suspect that the new functionality will be in the `DatalinkResultsMixin` by potentially adding a batch size argument maybe?

**Comment by andamian** [comment]
@funbaker - please let me know your opinion on this. What I'm after is the ability to retrieve datalink info in batches rather than individual calls for each record. It doesn't seem to be supported at the moment. Please let me know if you have a suggestion better than the one I've proposed. Tomorrow, I'm attempting an implementation. Thanks

**Comment by msdemlei** [comment]
On Wed, Feb 26, 2020 at 01:53:08AM -0800, andamian wrote:
> Current implementation requires separate calls to DataLink for each
> of the records in the results returned by an SIA or TAP query. In
> practice, this sometimes proves inefficient.
> 
> I propose an optimization by which the API allows the user to send
> multiple IDs (batches) to the DataLink service. I suspect that the
> new functionality will be in the `DatalinkResultsMixin` by
> potentially adding a batch size argument maybe?

This was certainly the intent of making ID repeatable in datalink; I
have a hunch this will become a bit tedious with associated
services, but I'd hope at least DaCHS services will do the right
thing for multiple ids.  You could try this with matches from, for
instance, the SSA service at
http://dc.zah.uni-heidelberg.de/feros/q/ssa/ssap.xml?

Other than that, I'm all for exposing multi-ID in pyVO just about
now, because right now no client I'm aware of does multi-ID, and that
means that related bugs in services will accumulate over time.

**Comment by andamian** [comment]
@msdemlei thanks. we've been using multi IDs with the cadc DataLink service just not through `pyvo`.  Good to know that I have another service to test against.
