### ISSUE TITLE
[Feature request] Allow proxy settings to be passed to requests

### ISSUE THREAD

**Issue by msbentley** [astropy/pyvo#291]
I have a use case (I don't know how common it is) to be able to access various services during development, when they are not publically available but may need to be access e.g. through a proxy. In my case I can use an SSH tunnel and socks5, which is supported "out-of-the-box" by requests (see e.g. https://docs.python-requests.org/en/latest/user/advanced/).

It would be great if the proxies argument could be passed to `requests`. I understand I can work around this for now by setting the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, so it's definitely low priority, but having it in code would allow greater flexibility.

**Comment by msdemlei** [comment]
On Tue, Jan 18, 2022 at 05:02:20AM -0800, Mark S. Bentley wrote:
> It would be great if the proxies argument could be passed to
> `requests`. I understand I can work around this for now by setting
> the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, so it's
> definitely low priority, but having it in code would allow greater
> flexibility.

Would perhaps

  import os
  os.environ["HTTP_PROXY"] = "http://my-pro.xy"

already fit your bill?  You see, since the use of proxies in general
is a very local thing, my first instinct is that we shouldn't really
encourage this kind of thing by giving an explicit API -- it lets
people cause really non-local failures (the developer sets a proxy in
module A and a request in module B fails for some other user because
the proxy isn't reachable for them).

**Comment by msbentley** [comment]
Yes, that would work (and does work) fine. You're right, this is too niche an issue - I'll close the ticket. Thanks!
