### ISSUE TITLE
Warning on QUERY_STATUS=OVERFLOW

### ISSUE THREAD

**Issue by andamian** [astropy/pyvo#322]
A `TAP` query returns a `QUERY_STATUS='OVERFLOW'` when the number of rows in the result exceeds `MAXREC` (set by the caller or the service), or the execution duration exceeds a threshold in the server or, in case of a async query, when the size of the results exceeds an output limit. While the result status can be easily determined with `result.query_status`, this is not always obvious for the caller especially when the result is returned via an intermediate package.

I think a warning would be more appropriate in this case. The user has the option of ignoring it or not. I've recently debugged a user problem in which the async query returned a weird number of rows and the culprit turned out to be `OVERFLOW`. This could have been easily avoided with such a warning.

Opinions?

I haven't looked at the `QUERY_STATUS='ERROR'` case.

**Comment by msdemlei** [comment]
On Thu, May 05, 2022 at 04:24:31PM -0700, Adrian wrote:
> Opinions?

Definitely +1 on issuing a warning.

> I haven't looked at the `QUERY_STATUS='ERROR'` case.

IIRC that's translated into an exception at least on sync.  I'd have
to look up myself what happens when in async, but I'm pretty sure I'd
have insisted on not siliently passing over errors in that case
either.
