### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by andamian** [astropy/pyvo#352]
This originates from a user:

I would like to see a useful error message in case I try to download proprietary data. That error message should also suggest that the user authenticates and gives a hint on how to do so.
Currently the output of pyvo when trying to download proprietary ALMA data is

```
 Traceback (most recent call last):
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/adhoc.py", line 237, in getdatalink
    datalink = self._results.get_adhocservice_by_ivoid(DATALINK_IVOID)
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/adhoc.py", line 146, in get_adhocservice_by_ivoid
    raise DALServiceError(
pyvo.dal.exceptions.DALServiceError: No Adhoc Service with ivo-id ivo://ivoa.net/std/datalink!

During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/adhoc.py", line 247, in getdataset
    url = next(self.getdatalink().bysemantics('#this')).access_url
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/adhoc.py", line 242, in getdatalink
    return DatalinkResults.from_result_url(self.getdataurl())
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/query.py", line 284, in from_result_url
    votableparse(cls._from_result_url(result_url, session).read),
  File "/home/userid/.local/lib/python3.8/site-packages/astropy/utils/decorators.py", line 536, in wrapper
    return function(*args, **kwargs)
  File "/home/userid/.local/lib/python3.8/site-packages/astropy/io/votable/table.py", line 166, in parse
    return tree.VOTableFile(
  File "/home/userid/.local/lib/python3.8/site-packages/astropy/io/votable/tree.py", line 3573, in parse
    for start, tag, data, pos in iterator:
ValueError: 1:0: syntax error

During handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/query.py", line 814, in cachedataset
    inp = self.getdataset(timeout)
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/utils/decorators.py", line 10, in wrapper
    raw = func(*args, **kwargs)
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/adhoc.py", line 253, in getdataset
    return super().getdataset(timeout=timeout)
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/utils/decorators.py", line 10, in wrapper
    raw = func(*args, **kwargs)
  File "/home/userid/.local/lib/python3.8/site-packages/pyvo/dal/query.py", line 766, in getdataset
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://almascience.eso.org/dataPortal/member.uid___A001_X14c3_X125d.README.txt
```

How to reproduce (as long as the MOUS is really still proprietary):

```
import os
import pyvo
datalink = pyvo.dal.adhoc.DatalinkResults.from_result_url("https://almascience.eso.org/datalink/sync?ID=uid://A001/X14c3/X125d")
for dl in datalink:
    dl.cachedataset(filename=os.path.basename(dl['access_url']))
```

**Comment by andamian** [comment]
I've tried to reproduce it myself. The generated trace is a bit simpler:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/adriand/Documents/work/github/pyvo/pyvo/dal/query.py", line 823, in cachedataset
    inp = self.getdataset(timeout)
  File "/Users/adriand/Documents/work/github/pyvo/pyvo/utils/decorators.py", line 9, in wrapper
    raw = func(*args, **kwargs)
  File "/Users/adriand/Documents/work/github/pyvo/pyvo/dal/adhoc.py", line 250, in getdataset
    response.raise_for_status()
  File "/Users/adriand/Documents/work/github/pyvo/.tox/py39-test/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: https://almascience.eso.org/dataPortal/member.uid___A001_X14c3_X125d.J1743-0350_ph.spw16.mfs.I.mask.fits.gz
```

Note that the message of the error is :`403 Forbidden: anonymous cannot access member.uid___A001_X14c3_X125d.J1743-0350_ph.spw16.mfs.I.mask.fits.gz'`

I don't know how this could be improved except maybe to come up with a set of dedicated errors that map the HTTP Error codes. But this is just a library that is used oftentimes with other code that makes HTTP calls and has to deal with the same type of errors. Handling these errors at the application level is therefore better.

Other opinions?

**Comment by bsipocz** [comment]
Similar cases came up in astroquery but we don't yet have a generic solution to do this. 
But the conclusion was that in many cases indeed be nice to expose e.g. `response.text` in these cases for more info.

Unfortunately I don't know how to do that rather than the very ugly workarounds with a try/except around L250 (raise_for_status), in astroquery we mostly deal with non-errenous HTTP responses and have to parse out the query errors from a non failing 200 status rather than from a raised exception.


So this try/except would be fine for this case, but how reliable it is to put a one-liner error message in respose.text?

**Comment by bsipocz** [comment]
So, would something like this be more useful?

```
~/munka/devel/pyvo/pyvo/dal/adhoc.py in getdataset(self, timeout)
    250             response = self._session.get(url, stream=True, timeout=timeout)
    251             try:
--> 252                 response.raise_for_status()
    253             except HTTPError as error:
    254                 error.args = (f"Server response text: {response.text} Raised error: ", ) + error.args

~/.pyenv/versions/3.10.0/lib/python3.10/site-packages/requests/models.py in raise_for_status(self)
    951 
    952         if http_error_msg:
--> 953             raise HTTPError(http_error_msg, response=self)
    954 
    955     def close(self):

HTTPError: ('Server response text: 403 Forbidden: anonymous cannot access member.uid___A001_X14c3_X125d.J1743-0350_ph.spw16.mfs.I.mask.fits.gz Raised error: ', '403 Client Error:  for url: https://almascience.eso.org/dataPortal/member.uid___A001_X14c3_X125d.J1743-0350_ph.spw16.mfs.I.mask.fits.gz')
```

**Comment by andamian** [comment]
Good point. These are Web Services that return the error messages so the response text should be a simple text message with the details of the error. But is this guaranteed? What if an intermediate service (like a proxy) return the error and provides a detail html message. That could look pretty ugly.

**Comment by bsipocz** [comment]
Then maybe this is just a documentation issue, have a central, troubleshooting page that shows how to catch the exception or go into debug mode and look into the response text, or even simpler, to copy-paste the URL from the error message to a browser and see that it doesn't work.

**Comment by bsipocz** [comment]
(also, this case also highlights that one cannot even rely on the usual place for errors, e.g. `response.reason` should really be the place to give a reason for the status_code, one shouldn't parse the text to get it. Maybe that's a ticket to upstream to alma as here it's an empty string?
```
ipdb> response.reason
''
```

**Comment by andamian** [comment]
If the error message is the cause of this confusion, then I think that the missing `reason` in the server response is the main culprit. `raise_for_status` automatically adds the reason the text of the exception, but in this particular case this is missing. I'll confirm with ALMA that this indeed would be an acceptable solution. Thanks @bsipocz .

**Comment by msdemlei** [comment]
On Fri, Sep 09, 2022 at 03:55:33PM -0700, Adrian wrote:
> Good point. These are Web Services that return the error messages
> so the response text should be a simple text message with the
> details of the error. But is this guaranteed? What if an
> intermediate service (like a proxy) return the error and provides a
> detail html message. That could look pretty ugly.

The question of error signalling has haunted the VO for a long time,
too, and I *think* (without having actually looked -- sorry, too busy
right now) that the various DAL protocol implementations do what the
protocols prescribe for "protocol errors", i.e., errors arising while the
server-side protocol handler is running as expected.  For the record,
new protocols using VOTables should follow DALI in that,
https://ivoa.net/documents/DALI/20170517/REC-DALI-1.1.html#tth_sEc4.2.
It is regrettable, though, that there are no guarantees as to the
HTTP codes in DALI.

But as every other protocol, DALI acknowledges that there are errors
"at the HTTP level" (with things like 404 or 503 particularly
popular).

So... the "response text" above is difficult and depends a bit on the
protocol.  I'm afraid the general logic would have to looks somewhat
like this:

If the response code is 200(-ish), pass through to the protocol
handler to see if a DALI error is there and then raise exceptions as
appropriate for that.

(then do redirects; which I think pyVO usually has no reason to even
consider, as requests does that for us)

For other response codes, obtain an error text:

(a) for a VOTable payload (by content-type), try an interpretation as
a DALI error (services should be able to override this, as at least
SCS needs a different technique here).

(b) for a plain text payload, I think it's a good idea to just copy
it in (that would cover what we can reasonably cover of SODA).

(c) otherwise, I think the best we can do is make something with the
status code and the short explanation.  I don't think there's any
point trying to fiddle out an explaination from HTML error pages,
say.

I think the current pyVO code is not terribly far from this, though I
doubt (a) is even tried explicitly.  And it's mainly (b) and (c)
we're talking about here, I'd say.
