### ISSUE TITLE
Mismatch of pyvo.regsearch and heasarc online tool

### ISSUE THREAD

**Issue by SimoneMender** [astropy/pyvo#368]
### Description
I want to query information from the rass2rxs catalog using pyvo. Some results do not match with the results of the online tool of heasarc. In case of the source BL LAC and the parameter "bb_flux", the value is 3.24500e-12 using the online tool and 0.0 using pyvo. I'm not sure if this is a problem of pyvo, but I could be a problem of small numbers?! I put an example below for the source BL LAC, but I also see this problem for other sources (and also other small parameters, e.g. "plaw_flux").

### Steps to Reproduce

1. Reproduce results of pyvo

```python
import pyvo as vo
from astropy.coordinates import SkyCoord

services = vo.regsearch(servicetype='tap', keywords=['heasarc'])
table = services[0].service.tables["rass2rxs"]

coord = SkyCoord.from_name("BL LAC")
query = f'''
SELECT ra, dec, name, plaw_flux, hardness_ratio_1, hardness_ratio_2, exposure, bb_flux  FROM public.rass2rxs as cat where 
contains(point('ICRS',cat.ra,cat.dec),circle('ICRS',{coord.ra.deg},{coord.dec.deg},0.1))=1
'''
results = services[0].service.run_async(query, dtype="float64")

results.to_table()
```

2. Reproduce results of the heasarc online tool
- open https://heasarc.gsfc.nasa.gov/db-perl/W3Browse/w3table.pl?tablehead=name%3Drass2rxs&Action=More+Options
- select the parameter "bb_flux"
- Insert "BL LAC" in the field "Object Name or Coordinates:"
- Press the button "Start Search"

### System Details
Linux-4.15.0-193-generic-x86_64-with-glibc2.10
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10) 
[GCC 10.3.0]
Numpy 1.20.3
pyerfa 2.0.0.1
astropy 5.0.4
pyvo 1.3

**Comment by msdemlei** [comment]
Hm.  I'm stumped.  It's even odder.  The script

  import pyvo

  query = f'''
  SELECT 
  bb_flux*10000000  FROM public.rass2rxs as cat where
  contains(point('ICRS',cat.ra,cat.dec),circle('ICRS',330.680,42.277,0.1))=1
  '''
  results = pyvo.dal.TAPService("https://heasarc.gsfc.nasa.gov/xamin/vo/tap"
	  ).run_async(query)

that I tried in order to figure out what might be going on fails with
"Error[s] detected in query preprocessing", which is heasarc's way to
say that the ADQL is wrong.

However, running the query in TOPCAT succeeds (and bb_flux has
the right value even without anything multiplied to it).  I've made
sure that QUERY is unmangled when we pass it to _session.post, so
it wouldn't seem we're feeding heasarc anything different than TOPCAT
would.

Hm.  Tentatively, I'd suggest it's not (directly) pyvo's fault.  I'll
ask the heasarc folks -- it's much easier to debug this when you see
what the server sees...

**Comment by SimoneMender** [comment]
Thanks for checking TOPCAT results. And also for asking heasarc people!

About the DALQueryError: for me it looks like it originates from the `*10000000` in the string. Don't know if this is allowed in ADQL?! Anyhow your code worked for me after I removed it (but again with the wrong value).

**Comment by trjaffe** [comment]
This is a known issue with our service that is losing the metadata (e.g., the formatting of floats) in some cases.  I'll have to check on the status of the deployment of the fix.  In the mean time, it should work if you change async to sync.  Let me know if not.

**Comment by msdemlei** [comment]
On Tue, Oct 04, 2022 at 05:37:22AM -0700, Simone Mender wrote:
> About the DALQueryError: for me it looks like it originates from
> the `*10000000` in the string. Don't know if this is allowed in
> ADQL?! Anyhow your code worked for me after I removed it (but again

Yes, of course -- ADQL lets you put in wild expressions -- you could
write log10(sin(foo+power(bar-30))) if that's what you need.  And you
can write avg(...) of that and have the database work out the
average.

This is what stumped me: when queried with TOPCAT, heasarc did the
right thing and parsed the ADQL ok.  With pyVO, it did not, and that
means there's a bug *somewhere*.  We'll just have to figure out
where...

**Comment by SimoneMender** [comment]
Thanks a lot. Indeed, using sync works!

**Comment by trjaffe** [comment]
And now async should also work.  Thanks for the nudge.  I just nudged the developer who nudged the CI/CD pipeline and the fix that had been sitting around for a bit is now deployed.

**Comment by tomdonaldson** [comment]
Thanks @SimoneMender for reporting this, and thanks @msdemlei and @trjaffe for looking into it!  Closing this issue now.
