### ISSUE TITLE
BUG: notifyWarning is undefined

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#378]
@msdemlei - I'm not sure which warning you meant to raise in https://github.com/astropy/pyvo/blob/main/pyvo/utils/vocabularies.py#L57, shall we define a class for this?

(and clearly, this line is not hit by the CI as the issue was picked up by the linter only)

**Comment by msdemlei** [comment]
On Sun, Oct 16, 2022 at 08:49:58AM -0700, Brigitta Sipőcz wrote:
> @msdemlei - I'm not sure which warning you meant to raise in https://github.com/astropy/pyvo/blob/main/pyvo/utils/vocabularies.py#L57, shall we define a class for this?
> 
> (and clearly, this line is not hit by the CI as the issue was picked up by the linter only)

Uh, ouch.  That's a trace of this code's provenance; base.ui is
something in DaCHS (which has this vocabulary caching, too,
independently of pyVO at least for now).

This should of course become a normal (astropy?) warning.  If you
have preferences as to what and which, I'm grateful for suggestions.
Otherwise, I'd probably just put in a warnings.warn.

And on CI: Constructing a test case for this is rather involved --
first, cache a vocabulary from a (fake) network request, then, change
the time, then make the fake network request fail --, and what's
caught here is rare (ivoa.net is down or has messed up its paths), so
I'd say that's a case where accepting a hole in test coverage is
entirely acceptable.

**Comment by bsipocz** [comment]
> This should of course become a normal (astropy?) warning.  If you
have preferences as to what and which, I'm grateful for suggestions.
Otherwise, I'd probably just put in a warnings.warn.

We have a `PyvoUserWarning`, I think that would do it well here.
