### ISSUE TITLE
DALQueryError when looking for epntap resources

### ISSUE THREAD

**Issue by rsav** [astropy/pyvo#393]
Hello,

I can't get the resources associated with an epntap datamodel.
I am using the current github version of pyvo.

To reproduce the problem:
```
In [1]: import pyvo as vo

In [2]: vo.version.version
Out[2]: '1.5.dev25+g5c443c5'

In [3]: from pyvo import registry

In [4]: registry.search(registry.Datamodel('epntap'))
---------------------------------------------------------------------------
DALQueryError                             Traceback (most recent call last)
<ipython-input-4-1efca414d656> in <module>
----> 1 registry.search(registry.Datamodel('epntap'))

~/tmp/pyvo/pyvo/registry/regtap.py in search(includeaux, maxrec, *constraints, **kwargs)
    154         get_RegTAP_query(*constraints, includeaux=includeaux, **kwargs),
    155         maxrec=maxrec)
--> 156     return query.execute()
    157
    158

~/tmp/pyvo/pyvo/registry/regtap.py in execute(self)
    172            for errors parsing the VOTable response
    173         """
--> 174         return RegistryResults(self.execute_votable(), self.queryurl)
    175
    176

~/tmp/pyvo/pyvo/dal/query.py in __init__(self, votable, url, session)
    319         self._status = self._findstatus(votable)
    320         if self._status[0].lower() not in ("ok", "overflow"):
--> 321             raise DALQueryError(self._status[1], self._status[0], url)
    322
    323         if self._status[0].lower() == "overflow":

DALQueryError: Field query: Could not parse your query: Expected boolean expression, found ':'  (at char 647), (line:13, col:22)
```

Could you confirm, help ?

Thanks
Renaud.

**Comment by msdemlei** [comment]
On Fri, Jan 06, 2023 at 06:00:36AM -0800, Renaud Savalle wrote:
> DALQueryError: Field query: Could not parse your query: Expected boolean expression, found ':'  (at char 647), (line:13, col:22)
> 
> Could you confirm, help ?

Oh gosh.  Silly typo, and a good illustration that misdesigns come at
a cost.  I can say that because the design is mine: dataModel in
RegTAP.  That's plain wrong, and therefore there is no common pattern
how to discover TAP-implemented data models, and therefore each DM
has extra code.  The query generator for EPN-TAP has a quote missing
in the ADQL generation (and that was even missing in the test case.
Blush).

Though I generally try to avoid tests doing too many network
connections, I think this failure tells me we'll really have to
exercise each of these separately, as for the time being the entire
DM discovery is just too messy.

PR #395 fixes this (both the missing quote and the test case).  Could
someone review it?

Meanwhile, the quick fix is to just open pyvo/registry/rtcons.py and
add a single quote in the line

  f"table_utype LIKE {pat}'" for pat in

to make it
  
  f"table_utype LIKE '{pat}'" for pat in

Sorry about this...
