### ISSUE TITLE
MAINT: improve test coverage of regtap

### ISSUE THREAD

**Issue by bsipocz** [astropy/pyvo#425]
Currently, it's only 55% with missing coverage of numerous methods leading to wonder whether hash-based splitting of standardid works as intended for services with IDs including a hash, e.g. the distinction of SIA and SIA2.

https://github.com/astropy/pyvo/blob/main/pyvo/registry/regtap.py#L311
https://github.com/astropy/pyvo/blob/main/pyvo/registry/regtap.py#L338

**Comment by msdemlei** [comment]
On Tue, Feb 21, 2023 at 12:44:43PM -0800, Brigitta Sipőcz wrote:
> Currently, it's only 55% with missing coverage of numerous methods
> leading to wonder whether hash-based splitting of standardid works
> as intended for services with IDs including a hash, e.g. the
> distinction of SIA and SIA2.

Umm... where do you get the 55% from?  I see about 80%, and quite a
bit of what's not covered is really crufty mess (regionOfRegard, say,
or the legacy ivoid2service that's been a bad idea to begin with);
but you're right, this needs to improve.  I'll do that.

**Comment by bsipocz** [comment]
Oh, indeed, my mistake, I'm sorry. I was running only the remote_data tests to get that number, running all of them indeed gets it to a much higher, 92% level.

**Comment by msdemlei** [comment]
On Wed, Feb 22, 2023 at 08:43:39AM +0100, Markus Demleitner wrote:
> Umm... where do you get the 55% from?  I see about 80%, and quite a
> bit of what's not covered is really crufty mess (regionOfRegard, say,
> or the legacy ivoid2service that's been a bad idea to begin with);
> but you're right, this needs to improve.  I'll do that.

Umm, again... before I dig: do we understand how the coverage
information at
https://app.codecov.io/gh/astropy/pyvo/blob/main/pyvo/registry/regtap.py
is obtained?  It would seem to me that it was generated without
remote data tests, which makes things somewhat ugly here.  For
instance, it is easy to ascertain that get_contact is exercised with
--remote-data=any, whereas it's shown as uncovered by codecov.io.

From what I see as otherwise uncovered, I've added two little tests
in PR #427.  This would still leave ivoid2service.  I think that's a
terrible interface, and testing it would either require at least 3
RegTAP queries (with remote data) or about as many fixtures, which
really seems over the top for something that I think nobody likes.

Can we just deprecate ivoid2service and say people should be using

res = regtap.search(ivoid=...)

and then do standard interface selection?  I think that'd be enough
of an excuse to not go into the trouble of testing it.

**Comment by bsipocz** [comment]
> Umm, again... before I dig: do we understand how the coverage
information at

I was running coverage tests locally with `pytest --cov pyvo --remote-data`, or running only the remote-data ones with `pytest -m remote_data --cov pyvo --remote-data`, and then I was looking directly at the `coverage html` generated html pages.

**Comment by bsipocz** [comment]
> When we deprecate ivoid2service, can we then close this bug? And is there a quick guide to deprecating in the astropy universe?

There isn't really any guide written, depending on the spread of usage the rule of thumb is to deprecate at least one release cycle, possibly more if it's widely used. Deprecations are usually dealt with by these decorators, but it's not mandatory, if it's a standalone function, manually raising the warning is just, as usual, a process as using the decorators. 

https://docs.astropy.org/en/stable/utils/index.html#id5
