### ISSUE TITLE
Registry search with Author fails

### ISSUE THREAD

**Issue by zoghbi-a** [astropy/pyvo#514]
An author-based query for the registry like this:
```python
from pyvo import registry as reg
reg.search(author='%HEASARC%') # or other names
# or
reg.search(reg.Author('%HEASARC%'))
```
gives:
```
Field query: No such field known: column 'role_name' could not be located in table metadata
```

isn't his how the author search meant to work?

**Comment by bsipocz** [comment]
I don't see this being covered in the tests either, so in addition to fixing the bug we'll need to make sure that the search constraint are better tested

**Comment by msdemlei** [comment]
On Tue, Jan 23, 2024 at 12:17:16AM -0800, Manon Marchand wrote:
> Looks like a missing `self._extra_tables = ["rr.res_role"]` in the
> init of the Author constraint.

Exactly -- that extra table admittedly is not tested, and it clearly
should.  Manon -- do you want to prepare the PR since it's really your
fix?  I'm terribly busy right until Thursday and might make a hash of
it...

> Do you think these should be remote tests?

We *really* don't want lots of remote tests for these to be run on
every test run; we had the question of perhaps creating an extra big
test suite to be run before releases already a while ago, but that's
again a question of who will write it.

On the other hand, one integration-type test that has all the
constraints, runs the query and checks that there's no error might be
a good way to prevent further stupid bugs like these.  I'd take a bug
to that effect on me.

**Comment by ManonMarchand** [comment]
Hi Markus, 
I can open the PR for the fix and add a single remote test with every constraints, sure.

**Comment by ManonMarchand** [comment]
Should be ok with the PR? Thanks for reporting this issue @zoghbi-a ! :slightly_smiling_face:
